version: '3'

services:
   db_app_2:
     container_name: db_app_2
     restart: always
     image: postgres:12
     environment:
       - POSTGRES_PASSWORD=${DB_PASSWORD}

   web_app_d_2:
     container_name: web_app_2
     restart: always
     build:
       dockerfile: ./web_app_2.dockerfile
       context: .
     ports:
       - "8001:8001"
     depends_on:
       - db_app_2

networks:
  production-network:
    driver: bridge
